package app.rockkworld.com.mproject.utils;

import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.Hashtable;

import app.rockkworld.com.mproject.model.UserMetaDetail;

/**
 * Created by divya on 10/8/15.
 */
public interface TestConstants {


    String RESPONSE_NEWSFEEDS="{\"user_post\":[{\"id\":\"1\",\"uid\":\"1\",\"timestamp\":\"20 minutes ago\",\"msg\":\"Put your heart, mind, and soul into even your smallest acts. This is the secret of success.\",\"like\":10,\"dislike\":0,\"commentsCount\":0,\"tag\":[],\"sharedby\":[]},{\"id\":\"2\",\"uid\":\"1\",\"timestamp\":\"3 hours ago\",\"msg\":\"The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.\",\"like\":1,\"dislike\":0,\"commentsCount\":3,\"tag\":[],\"sharedby\":[]},{\"id\":\"3\",\"uid\":\"4\",\"timestamp\":\"10 hours ago\",\"msg\":\"\",\"img\":[\"1\"],\"like\":20,\"dislike\":0,\"commentsCount\":10,\"tag\":[],\"sharedby\":[]},{\"id\":\"4\",\"uid\":\"4\",\"timestamp\":\"10 hours ago\",\"msg\":\"Team outing... so much fun \",\"img\":[\"2\"],\"like\":10,\"dislike\":0,\"commentsCount\":10,\"tag\":[],\"sharedby\":[]},{\"id\":\"5\",\"uid\":\"5\",\"timestamp\":\"10 hours ago\",\"msg\":\"\",\"img\":[\"3\"],\"like\":10,\"dislike\":0,\"commentsCount\":10,\"tag\":[],\"sharedby\":[]},{\"id\":\"6\",\"uid\":\"3\",\"timestamp\":\"7 Aug\",\"msg\":\"\",\"img\":[\"5\"],\"like\":4,\"dislike\":0,\"commentsCount\":8,\"tag\":[\"1\",\"2\"],\"sharedby\":[]},{\"id\":\"7\",\"uid\":\"3\",\"timestamp\":\" 09 Aug 2015 09:10 PM\",\"msg\":\"\",\"img\":[\"6\"],\"like\":4,\"dislike\":0,\"commentsCount\":8,\"tag\":[\"1\",\"2\"],\"sharedby\":[]},{\"id\":\"8\",\"uid\":\"4\",\"timestamp\":\"10 hours ago\",\"msg\":\"\",\"img\":[\"7\"],\"like\":20,\"dislike\":0,\"commentsCount\":10,\"tag\":[],\"sharedby\":[]},{\"id\":\"9\",\"uid\":\"4\",\"timestamp\":\"10 hours ago\",\"msg\":\"Group Picture Session..:)\",\"img\":[\"8\"],\"like\":20,\"dislike\":0,\"commentsCount\":10,\"tag\":[],\"sharedby\":[]},{\"id\":\"10\",\"uid\":\"4\",\"timestamp\":\"10 hours ago\",\"msg\":\"\",\"img\":[\"9\"],\"like\":20,\"dislike\":0,\"commentsCount\":10,\"tag\":[],\"sharedby\":[]},{\"id\":\"11\",\"uid\":\"4\",\"timestamp\":\"10 hours ago\",\"msg\":\"\",\"img\":[\"10\"],\"like\":20,\"dislike\":0,\"commentsCount\":10,\"tag\":[],\"sharedby\":[]},{\"id\":\"12\",\"uid\":\"4\",\"timestamp\":\"10 hours ago\",\"msg\":\"\",\"img\":[\"11\"],\"like\":20,\"dislike\":0,\"commentsCount\":10,\"tag\":[],\"sharedby\":[]},{\"id\":\"13\",\"uid\":\"4\",\"timestamp\":\"10 hours ago\",\"msg\":\"\",\"img\":[\"12\"],\"like\":20,\"dislike\":0,\"commentsCount\":10,\"tag\":[],\"sharedby\":[]},{\"id\":\"14\",\"uid\":\"4\",\"timestamp\":\"10 hours ago\",\"msg\":\"\",\"img\":[\"13\"],\"like\":20,\"dislike\":0,\"commentsCount\":10,\"tag\":[],\"sharedby\":[]}],\"user\":{\"1\":{\"name\":\"Nikhil Taneja\",\"dp\":\"1\"},\"2\":{\"name\":\"Ankit Gupta\",\"dp\":\"2\"},\"3\":{\"name\":\"Neetu Goyal\",\"dp\":\"3\"},\"4\":{\"name\":\"Rohan Raj\",\"dp\":\"4\"},\"5\":{\"name\":\"Akash\",\"dp\":\"5\"}}}";
    String RESPONSE_COMMENTS="{\"startIndex\":0,\"count\":10,\"maxCount\":10,\"comments\":[{\"id\":\"1\",\"uid\":\"1\",\"username\":\"Akhil\",\"msg\":\"Superub..\",\"image\":\"\",\"ts\":\"10 mins ago \"},{\"id\":\"2\",\"uid\":\"2\",\"username\":\"Rohan\",\"msg\":\"Super Like\",\"image\":\"\",\"ts\":\"15 mins ago\"},{\"id\":\"3\",\"uid\":\"3\",\"username\":\"Himanshu\",\"msg\":\"Awsome\",\"image\":\"\",\"ts\":\"1 hour ago\"},{\"id\":\"4\",\"uid\":\"5\",\"username\":\"Reena\",\"msg\":\"superub...\",\"image\":\"\",\"ts\":\"1 hour ago\"},{\"id\":\"5\",\"uid\":\"5\",\"username\":\"Radhika\",\"msg\":\"yeahh... \",\"image\":\"\",\"ts\":\"1 day ago\"}]}";
    String RSPONSE_LIKES="{\"startIndex\":0,\"count\":10,\"maxCount\":10,\"Likes\":[{\"name\":\"Nikhil Taneja\",\"dp\":\"1\",\"ts\":\"10 mins ago\"},{\"name\":\"Ankit Gupta\",\"dp\":\"2\",\"ts\":\"25 mins ago\"},{\"name\":\"Neetu Goyal\",\"dp\":\"3\",\"ts\":\"2hours ago\"},{\"name\":\"Rohan Raj\",\"dp\":\"4\",\"ts\":\"1 day ago\"},{\"name\":\"Akash\",\"dp\":\"5\",\"ts\":\"1 day ago\"}]}";
    String RSPONSE_DISLIKES="{\"startIndex\":0,\"count\":10,\"maxCount\":10,\"Dislikes\":[{\"name\":\"Nikhil Taneja\",\"dp\":\"1\",\"ts\":\"10 mins ago\"},{\"name\":\"Ankit Gupta\",\"dp\":\"2\",\"ts\":\"25 mins ago\"},{\"name\":\"Neetu Goyal\",\"dp\":\"3\",\"ts\":\"2hours ago\"},{\"name\":\"Rohan Raj\",\"dp\":\"4\",\"ts\":\"1 day ago\"},{\"name\":\"Akash\",\"dp\":\"5\",\"ts\":\"1 day ago\"}]}";
}
